version: "3"
services:
  app:    
    image: brandnewbox/bnb-ruby:2.7-postgresql
    command: bundle exec puma -C config/puma.rb
    volumes:
      - .:/app:cached
      - bundle_cache:/usr/local/bundle
    ports:
      - "3000:3000"
    depends_on:
      - postgres
  postgres:
    image: postgres:11-alpine
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - '5433:5432'
    volumes:
      - my_dbdata:/var/lib/postgresql/data
volumes:
  bundle_cache:
  my_dbdata: